### ISSUE TITLE
The client can't load

### ISSUE THREAD

**Issue by UnspeakableKinG** [depressionclient/issues#5]
when I open the client everything start smoothly, the client logo appears but after that The screen turns black, and when i click the JVM stop responding!
log files: https://pastebin.com/ZR3q4eXT

**Comment by Mat1337** [comment]
have you tried to delete the Depression Folder in .minecraft and restarting the client

**Comment by UnspeakableKinG** [comment]
There wasn't any depression folder but i used a new .minecraft folder and it worked! I think the problem was the settings i have.
