### ISSUE TITLE
Depression does not start in tlauncher

### ISSUE THREAD

**Issue by Leneleshe** [depressionclient/issues#6]
The client does not respond when started

**Comment by Mat1337** [comment]
yes I am aware of the issue it is due to a discord library messing up, working on a fix.

**Comment by Leneleshe** [comment]
> yes I am aware of the issue it is due to a discord library messing up, working on a fix.

And how to fix it?

**Comment by Mat1337** [comment]
just have discord open for now

**Comment by Leneleshe** [comment]
I hope in the new version everything will be fine, right?

**Comment by Mat1337** [comment]
yes it will be fixed
